using JoinNCFiles_DTVM.Joinners.MC3000.Abstraction;
using System;
using System.Collections.Generic;
using System.IO;
using System.Text;

namespace JoinNCFiles_DTVM
{
    /// <summary>
    /// Joining NC files generated by the postprocesor MC3000
    /// </summary>
    public class MC3000 : IJoinNCfile
    {
        private int lineNo = 10;
        private readonly MC3000Settings settings;
        private readonly IMC3000FileNamesManipulator _fileNameManipulator;
        private readonly string resultNCfileName = string.Empty;

        /// <summary>
        /// Joinner for machine MC3000
        /// </summary>
        /// <param name="settings">Settings file inherited from BaseData</param>
        public MC3000(BaseData settings, IMC3000FileNamesManipulator fileNameManipulator)
        {
            this.settings = (MC3000Settings)settings;
            _fileNameManipulator = fileNameManipulator;
        }

        /// <summary>
        /// Joins NC files generated in the same folder with the same name and incremented suffix
        /// </summary>
        /// <param name="lastGeneratedNCfile">Last generated NC file</param>
        public void JoinFiles(string lastGeneratedNCfile)
        {
            _fileNameManipulator.ManipulateFileNames(lastGeneratedNCfile);

            Join(false, _fileNameManipulator.ToolSheetResult, _fileNameManipulator.toolSheetResults);

            Join(true, _fileNameManipulator.NCfileResult, _fileNameManipulator.ncFileResults);

            AddToolSheetToNCfile();
        }

        /// <summary>
        /// Joins files generated with the pattern xxx_N.nc
        /// xxx -> constatnt name of the file
        /// N -> suffix number, orders files existing in the same folder
        /// </summary>
        /// <param name="insertLine">flag if insert line numbers</param>
        /// <param name="result">name of the resulting file</param>
        /// <param name="paths">list of files to join</param>
        private void Join(bool insertLine, string result, List<string> paths)
        {
            string str;
            Encoding defaultEncoding = Encoding.GetEncoding(Encoding.Default.CodePage, new EncoderExceptionFallback(), new DecoderExceptionFallback());

            //delete if any result file exists
            Delete(result);

            foreach (String file in paths)
            {
                using (TextWriter tw = new StreamWriter(Path.GetFullPath(result), true, defaultEncoding))
                {
                    using (StreamReader tr = new StreamReader(file, defaultEncoding))
                    {
                        while (!tr.EndOfStream)
                        {
                            str = tr.ReadLine();
                            if (insertLine)
                                tw.WriteLine(Renumber(str, ref this.lineNo));
                            else
                                tw.WriteLine(str);
                        }
                        tr.Close();
                    }
                    tw.Close();
                }
            }
        }

        /// <summary>
        /// Reads all toolsheets lines
        /// </summary>
        /// <returns>List of toolsheets lines</returns>
        private List<string> GetToolSheet()
        {
            var allLines = File.ReadAllLines(_fileNameManipulator.ToolSheetResult, Encoding.Default);
            //var allLines = File.ReadAllLines(ToolSheetResult, Encoding.Default);
            List<string> lines = new List<string>(allLines);
            return lines;
        }

        /// <summary>
        /// Inserts toolsheets lines right after the string  "(OSAZENI ZASOBNIKU)"
        /// </summary>
        private void AddToolSheetToNCfile()
        {
            var allLines = File.ReadAllLines(_fileNameManipulator.NCfileResult, Encoding.Default);
            //var allLines = File.ReadAllLines(this.NCfileResult, Encoding.Default);
            List<string> lines = new List<string>(allLines);
            int index = lines.IndexOf(this.settings.Settingrows[0].InsertToolingList);
            lines.InsertRange(index + 1, GetToolSheet());
            File.WriteAllLines(_fileNameManipulator.NCfileResult, lines.ToArray());
            //File.WriteAllLines(this.NCfileResult, lines.ToArray());
        }


        /// <summary>
        /// Deletes a resulting file in case that exists from the previous run
        /// </summary>
        /// <param name="file">File to delete</param>
        private void Delete(string file)
        {
            try
            {
                FileInfo NCfile = new FileInfo(file);
                if (NCfile.Exists)
                    NCfile.Delete();
                NCfile = null;
            }
            catch (Exception e)
            {
                Console.WriteLine("Chyba ... " + e.StackTrace +
                    Environment.NewLine + Environment.NewLine +
                    e.Message + Environment.NewLine + Environment.NewLine +
                    e.TargetSite);
                Console.WriteLine("Program bude ukončen libovolnou klávesou.");
                Console.ReadKey();
            }
        }
        /// <summary>
        /// Adds line numbers
        /// </summary>
        /// <param name="input">Actual line for prefixing via a line No.</param>
        /// <param name="num">Actual line No.</param>
        /// <returns>Nacteny radek doplneny o cislo radku</returns>
        private string Renumber(string input, ref int num)
        {
            string ret = input;

            if (input.StartsWith(")"))
            {
                ret = ("(" + num.ToString()).PadRight(1, ' ') + input;
                num += 10;
            }

            if (input.StartsWith(" N"))
            {
                input = input.Replace("N", "N" + num.ToString()).PadRight(1, ' ');
                ret = input.Replace("R800=", " R800=" + num.ToString()).PadRight(1, ' ');
                num += 10;
            }
            return ret;
        }
    }
}
