using JoinNCFiles_DTVM.Joinners.MC3000;
using JoinNCFiles_DTVM.Joinners.MC3000.Abstraction;
using System;
using System.IO;
using System.Text.RegularExpressions;

namespace JoinNCFiles_DTVM
{
    public class JoinFactory
    {
        /// <summary>
        /// Creates a joinner for joining NC files generated by a particular posptprocesor
        /// </summary>
        /// <param name="postprocesor">Postprocesor's name AAAA_XXXX_XXXX.mcp where AAAA stands for the name of machine, eg.MC3001</param>
        /// <returns></returns>
        public static IJoinNCfile CreateJoinner (string postprocesor)
        {
            if (!postprocesor.Contains("_"))
                new ArgumentException();
            
            //find where settings.xml file is and read it
            string appPath = System.Reflection.Assembly.GetExecutingAssembly().Location;
            var directory = System.IO.Path.GetDirectoryName(appPath);

            string untilUnderscore(string s) { return (new Regex("^(.*?)_")).Match(s).Groups[1].ToString(); }

            if (untilUnderscore(postprocesor).ToUpper().Equals("MC3001"))
            {
                var reader = MC3000SettingReader.Instance;
                BaseData setting = (MC3000Settings)reader.ReadData(Path.Combine(directory, @"MC3000SETTINGS.xml"));
                IMC3000FileNamesManipulator fileNameManipulator = new MC3000FileNameManipulator();
                //create and return joinner for particular postprocesor
                return new MC3000(setting, fileNameManipulator);
            } else if (untilUnderscore(postprocesor).Equals("WACO3"))
            {
                //not ready eyt
                throw new NotImplementedException();
            }

            throw new ArgumentException();
        }
    }


}
